{% set name = "moraine" %}
<<<<<<< 0.8.3_h03ac28
{% set version = "0.8.3" %}
=======
{% set version = "0.8.1" %}
{% set python_min = "3.10" %}
>>>>>>> main

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/moraine-{{ version }}.tar.gz
<<<<<<< 0.8.3_h03ac28
  sha256: fce77d495b9045d93afe011cbcca0d20b83b79062000fc573aa03ad9a3380aac
=======
  sha256: be8956eb9fd7b1bed51141aaaa4284c3d5f991dfaede162bc4f1dd35c2747bcb
>>>>>>> main

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - matplotlib-base
    - fastcore
    - numba
    - dask
    - zarr
    - pyproj
    - tqdm
    - toml
    - numexpr
    - numcodecs
    - pandas
    - holoviews
    - datashader
    - colorcet
    - spatialpandas

test:
  imports:
    - moraine
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kanglcn/moraine
  summary: Modern Radar Interferometry Environment, A simple, stupid InSAR postprocessing tool in big data era
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kanglcn
