{% set name = "moraine" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/moraine-{{ version }}.tar.gz
  sha256: b27247b14479d4930443c93eec16e9c54fa49e78852a74177ee4da076a4664fb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - scipy
    - matplotlib-base
    - fastcore
    - numba
    - dask
    - zarr
    - pyproj
    - tqdm
    - toml
    - numexpr
    - numcodecs
    - pandas
    - holoviews
    - datashader
    - colorcet
    - spatialpandas

test:
  imports:
    - moraine
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kanglcn/moraine
  summary: Modern Radar Interferometry Environment, A simple, stupid InSAR postprocessing tool in big data era
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kanglcn
