{% set name = "moraine" %}
{% set version = "0.9.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/moraine-{{ version }}.tar.gz
  sha256: 7981c8d5ad759f883d3fe0f0e4649c887683778b714b14d0615e2854f33ef81e

build:
  noarch: python
  number: 0
  script: |
    {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    # Force-install specific PyPI-only dependencies

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - matplotlib-base
    - fastcore
    - numba
    - dask
    - zarr
    - pyproj
    - tqdm
    - toml
    - numexpr
    - pandas
    - holoviews
    - colorcet
    - onnxruntime

test:
  imports:
    - moraine
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kanglcn/moraine
  summary: Modern Radar Interferometry Environment, A simple, stupid InSAR postprocessing tool in big data era
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kanglcn
