{% set name = "moraine" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/moraine-{{ version }}.tar.gz
  sha256: 0d26c34787d6e5fd1aed7044a9252d6aef5201fe0fc967120c8ed8c09214d87d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy
    - scipy
    - matplotlib-base

test:
  imports:
    - moraine
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kanglcn/moraine
  summary: Modern Radar Interferometry Environment, A simple, stupid InSAR postprocessing tool in big data era
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kanglcn
